/** The page name and the corresponding route URL records. */
export const PAGES: Record<PageName, PageUrl> = {
  'Page Not Found': '**',
  'Pip-Boy 2000 Mk VI Simulator': '2000-mk-vi',
  'Pip-Boy 3000 Mk IV Simulator': '3000-mk-iv',
  'Pip-Boy 3000 Mk V Apps': '3000-mk-v/apps',
  'Pip-Boy 3000 Mk V Companion App': '3000-mk-v',
  'Pip-Boy 3000 Mk V Maintenance': '3000-mk-v/maintenance',
  'Pip-Boy 3000 Mk V Radio': '3000-mk-v/radio',
  'Pip-Boy 3000 Simulator': '3000',
  'Pip-Boy 3000A Simulator': '3000a',
  'Privacy Policy': 'privacy-policy',
  Home: '',
  Login: 'login',
  Register: 'register',
  Status: 'status',
  'Terms and Conditions': 'terms-and-conditions',
  Vault: `vault/:id`,
  /** Pip-Boy 3000 Mk IV Routes */
  'DATA > QUESTS - Pip-Boy 3000 Mk IV': 'data/quests',
  'DATA > STATS - Pip-Boy 3000 Mk IV': 'data/stats',
  'DATA > WORKSHOPS - Pip-Boy 3000 Mk IV': 'data/workshops',
  'INV > AID - Pip-Boy 3000 Mk IV': 'inv/aid',
  'INV > APPAREL - Pip-Boy 3000 Mk IV': 'inv/apparel',
  'INV > WEAPONS - Pip-Boy 3000 Mk IV': 'inv/weapons',
  'MAP - Pip-Boy 3000 Mk IV': 'map',
  'RADIO - Pip-Boy 3000 Mk IV': 'radio',
  'STAT > PERKS - Pip-Boy 3000 Mk IV': 'stat/perks',
  'STAT > SPECIAL - Pip-Boy 3000 Mk IV': 'stat/special',
  'STAT > STATUS - Pip-Boy 3000 Mk IV': 'stat/status',
};
