const PIP_BOY_3000_MK_IV_PAGE_NAMES = [
  'DATA > QUESTS - Pip-Boy 3000 Mk IV',
  'DATA > STATS - Pip-Boy 3000 Mk IV',
  'DATA > WORKSHOPS - Pip-Boy 3000 Mk IV',
  'INV > AID - Pip-Boy 3000 Mk IV',
  'INV > APPAREL - Pip-Boy 3000 Mk IV',
  'INV > WEAPONS - Pip-Boy 3000 Mk IV',
  'MAP - Pip-Boy 3000 Mk IV',
  'RADIO - Pip-Boy 3000 Mk IV',
  'STAT > PERKS - Pip-Boy 3000 Mk IV',
  'STAT > SPECIAL - Pip-Boy 3000 Mk IV',
  'STAT > STATUS - Pip-Boy 3000 Mk IV',
] as const;

export const PAGE_NAMES = [
  'Forum',
  'Forum - Post',
  'Home',
  'Login',
  'My Vault',
  'Page Not Found',
  'Pip-Boy 2000 Mk VI Simulator',
  'Pip-Boy 3000 Mk IV Simulator',
  ...PIP_BOY_3000_MK_IV_PAGE_NAMES,
  'Pip-Boy 3000 Mk V Apps',
  'Pip-Boy 3000 Mk V Companion App',
  'Pip-Boy 3000 Mk V Maintenance',
  'Pip-Boy 3000 Mk V Radio',
  'Pip-Boy 3000 Simulator',
  'Pip-Boy 3000A Simulator',
  'Privacy Policy',
  'Register',
  'Status',
  'Support',
  'Terms and Conditions',
  'Verify Email',
] as const;
